//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lql.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Nimblesite.Lql.Core.Parsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILqlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LqlBaseListener : ILqlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] LqlParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] LqlParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] LqlParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] LqlParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.withStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithStmt([NotNull] LqlParser.WithStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.withStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithStmt([NotNull] LqlParser.WithStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.cteDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCteDef([NotNull] LqlParser.CteDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.cteDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCteDef([NotNull] LqlParser.CteDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.letStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetStmt([NotNull] LqlParser.LetStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.letStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetStmt([NotNull] LqlParser.LetStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.pipeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPipeExpr([NotNull] LqlParser.PipeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.pipeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPipeExpr([NotNull] LqlParser.PipeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] LqlParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] LqlParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.windowSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindowSpec([NotNull] LqlParser.WindowSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.windowSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindowSpec([NotNull] LqlParser.WindowSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.partitionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartitionClause([NotNull] LqlParser.PartitionClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.partitionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartitionClause([NotNull] LqlParser.PartitionClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderClause([NotNull] LqlParser.OrderClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderClause([NotNull] LqlParser.OrderClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderByArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderByArgList([NotNull] LqlParser.OrderByArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderByArgList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderByArgList([NotNull] LqlParser.OrderByArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderByArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderByArg([NotNull] LqlParser.OrderByArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderByArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderByArg([NotNull] LqlParser.OrderByArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.lambdaExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpr([NotNull] LqlParser.LambdaExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.lambdaExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpr([NotNull] LqlParser.LambdaExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedIdent([NotNull] LqlParser.QualifiedIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedIdent([NotNull] LqlParser.QualifiedIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] LqlParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] LqlParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg([NotNull] LqlParser.ArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg([NotNull] LqlParser.ArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.columnAlias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumnAlias([NotNull] LqlParser.ColumnAliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.columnAlias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumnAlias([NotNull] LqlParser.ColumnAliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arithmeticExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmeticExpr([NotNull] LqlParser.ArithmeticExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arithmeticExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmeticExpr([NotNull] LqlParser.ArithmeticExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arithmeticTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmeticTerm([NotNull] LqlParser.ArithmeticTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arithmeticTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmeticTerm([NotNull] LqlParser.ArithmeticTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arithmeticFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmeticFactor([NotNull] LqlParser.ArithmeticFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arithmeticFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmeticFactor([NotNull] LqlParser.ArithmeticFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] LqlParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] LqlParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.namedArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedArg([NotNull] LqlParser.NamedArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.namedArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedArg([NotNull] LqlParser.NamedArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpr([NotNull] LqlParser.LogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpr([NotNull] LqlParser.LogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] LqlParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] LqlParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.atomicExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicExpr([NotNull] LqlParser.AtomicExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.atomicExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicExpr([NotNull] LqlParser.AtomicExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] LqlParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] LqlParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.existsExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExistsExpr([NotNull] LqlParser.ExistsExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.existsExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExistsExpr([NotNull] LqlParser.ExistsExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.nullCheckExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullCheckExpr([NotNull] LqlParser.NullCheckExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.nullCheckExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullCheckExpr([NotNull] LqlParser.NullCheckExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.inExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInExpr([NotNull] LqlParser.InExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.inExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInExpr([NotNull] LqlParser.InExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.caseExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseExpr([NotNull] LqlParser.CaseExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.caseExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseExpr([NotNull] LqlParser.CaseExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.whenClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhenClause([NotNull] LqlParser.WhenClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.whenClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhenClause([NotNull] LqlParser.WhenClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.caseResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseResult([NotNull] LqlParser.CaseResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.caseResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseResult([NotNull] LqlParser.CaseResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderDirection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderDirection([NotNull] LqlParser.OrderDirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderDirection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderDirection([NotNull] LqlParser.OrderDirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.comparisonOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonOp([NotNull] LqlParser.ComparisonOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.comparisonOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonOp([NotNull] LqlParser.ComparisonOpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Nimblesite.Lql.Core.Parsing
