//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lql.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Nimblesite.Lql.Core.Parsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LqlParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILqlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LqlParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LqlParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] LqlParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] LqlParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithStmt([NotNull] LqlParser.WithStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithStmt([NotNull] LqlParser.WithStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.cteDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCteDef([NotNull] LqlParser.CteDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.cteDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCteDef([NotNull] LqlParser.CteDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetStmt([NotNull] LqlParser.LetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetStmt([NotNull] LqlParser.LetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.pipeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPipeExpr([NotNull] LqlParser.PipeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.pipeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPipeExpr([NotNull] LqlParser.PipeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] LqlParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] LqlParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.windowSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindowSpec([NotNull] LqlParser.WindowSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.windowSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindowSpec([NotNull] LqlParser.WindowSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartitionClause([NotNull] LqlParser.PartitionClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartitionClause([NotNull] LqlParser.PartitionClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderClause([NotNull] LqlParser.OrderClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderClause([NotNull] LqlParser.OrderClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderByArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderByArgList([NotNull] LqlParser.OrderByArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderByArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderByArgList([NotNull] LqlParser.OrderByArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderByArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderByArg([NotNull] LqlParser.OrderByArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderByArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderByArg([NotNull] LqlParser.OrderByArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.lambdaExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpr([NotNull] LqlParser.LambdaExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.lambdaExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpr([NotNull] LqlParser.LambdaExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdent([NotNull] LqlParser.QualifiedIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdent([NotNull] LqlParser.QualifiedIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] LqlParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] LqlParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] LqlParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] LqlParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumnAlias([NotNull] LqlParser.ColumnAliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumnAlias([NotNull] LqlParser.ColumnAliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticExpr([NotNull] LqlParser.ArithmeticExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticExpr([NotNull] LqlParser.ArithmeticExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arithmeticTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticTerm([NotNull] LqlParser.ArithmeticTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arithmeticTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticTerm([NotNull] LqlParser.ArithmeticTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.arithmeticFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticFactor([NotNull] LqlParser.ArithmeticFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.arithmeticFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticFactor([NotNull] LqlParser.ArithmeticFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] LqlParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] LqlParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.namedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedArg([NotNull] LqlParser.NamedArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.namedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedArg([NotNull] LqlParser.NamedArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpr([NotNull] LqlParser.LogicalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpr([NotNull] LqlParser.LogicalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] LqlParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] LqlParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.atomicExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicExpr([NotNull] LqlParser.AtomicExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.atomicExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicExpr([NotNull] LqlParser.AtomicExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] LqlParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] LqlParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExistsExpr([NotNull] LqlParser.ExistsExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExistsExpr([NotNull] LqlParser.ExistsExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.nullCheckExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullCheckExpr([NotNull] LqlParser.NullCheckExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.nullCheckExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullCheckExpr([NotNull] LqlParser.NullCheckExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.inExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInExpr([NotNull] LqlParser.InExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.inExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInExpr([NotNull] LqlParser.InExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.caseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseExpr([NotNull] LqlParser.CaseExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.caseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseExpr([NotNull] LqlParser.CaseExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenClause([NotNull] LqlParser.WhenClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenClause([NotNull] LqlParser.WhenClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.caseResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseResult([NotNull] LqlParser.CaseResultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.caseResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseResult([NotNull] LqlParser.CaseResultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.orderDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderDirection([NotNull] LqlParser.OrderDirectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.orderDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderDirection([NotNull] LqlParser.OrderDirectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LqlParser.comparisonOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOp([NotNull] LqlParser.ComparisonOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LqlParser.comparisonOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOp([NotNull] LqlParser.ComparisonOpContext context);
}
} // namespace Nimblesite.Lql.Core.Parsing
