//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lql.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Nimblesite.Lql.Core.Parsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LqlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] LqlParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LqlParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWithStmt([NotNull] LqlParser.WithStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.cteDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCteDef([NotNull] LqlParser.CteDefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStmt([NotNull] LqlParser.LetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.pipeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPipeExpr([NotNull] LqlParser.PipeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] LqlParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.windowSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowSpec([NotNull] LqlParser.WindowSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartitionClause([NotNull] LqlParser.PartitionClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderClause([NotNull] LqlParser.OrderClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.orderByArgList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderByArgList([NotNull] LqlParser.OrderByArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.orderByArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderByArg([NotNull] LqlParser.OrderByArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.lambdaExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpr([NotNull] LqlParser.LambdaExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdent([NotNull] LqlParser.QualifiedIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] LqlParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] LqlParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnAlias([NotNull] LqlParser.ColumnAliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExpr([NotNull] LqlParser.ArithmeticExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.arithmeticTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticTerm([NotNull] LqlParser.ArithmeticTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.arithmeticFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticFactor([NotNull] LqlParser.ArithmeticFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] LqlParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.namedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedArg([NotNull] LqlParser.NamedArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExpr([NotNull] LqlParser.LogicalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] LqlParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.atomicExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicExpr([NotNull] LqlParser.AtomicExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] LqlParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExistsExpr([NotNull] LqlParser.ExistsExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.nullCheckExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullCheckExpr([NotNull] LqlParser.NullCheckExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.inExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInExpr([NotNull] LqlParser.InExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.caseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseExpr([NotNull] LqlParser.CaseExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhenClause([NotNull] LqlParser.WhenClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.caseResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseResult([NotNull] LqlParser.CaseResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.orderDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderDirection([NotNull] LqlParser.OrderDirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LqlParser.comparisonOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOp([NotNull] LqlParser.ComparisonOpContext context);
}
} // namespace Nimblesite.Lql.Core.Parsing
